### ISSUE TITLE
Deck Renders Incorrect Fields For Variables

### ISSUE THREAD

**Issue by rossedman** [spinnaker/spinnaker#1983]
## Deck Renders Incorrect Fields For Variables

*Cloud Provider* - Kubernetes, Azure

*Environment* - Spinnaker 1.4.1, Kubernetes, Azure, AAD, Pipeline Templates

*Feature Area* - Pipeline Templates

*Description*

When creating a pipeline template the `type` field renders incorrect fields on the frontend that cause importing pipeline templates to fail.

*Steps to Reproduce*

1. Enable pipelines
2. Use this [gist](https://gist.githubusercontent.com/rossedman/2ab83ab55eafedd562d4848705baacba/raw/042e3faf78170489b5cf1be3e17f1ef13cc697aa/complex-wait) when importing a template
3. Submit
4. Enter `int` only, like `20` and `5`

The error that returns reads this:

```
Could not generate pipeline from provided template configuration.
Errors:
Message: failed rendering template expression
Severity: FATAL
Cause: Failed rendering stage
Message: malformed template configuration
Severity: FATAL
Cause: Incorrectly defined variable(s): waitTime (expected type 'int' found type 'String')
Message: malformed template configuration
Severity: FATAL
Cause: Incorrectly defined variable(s): waitTime (expected type 'int' found type 'String'), childWaitTime (expected type 'int' found type 'String')
```

**Comment by danielpeach** [comment]
Looks like this was solved here: https://github.com/spinnaker/deck/pull/4187

**Comment by rossedman** [comment]
@danielpeach cool look forward to the next release!

**Comment by rossedman** [comment]
@danielpeach Reopening, this is still an issue.

If I [use this template](https://github.com/spinnaker/dcd-spec/blob/master/examples/pipeline-templates-v1/complex-wait/root-template.yml), when the UI asks me for an a value and I give it an int it still throws errors in Orca. In the error below I provided the number 5.

```
{
  "errors" : [ {
    "severity" : "FATAL",
    "cause" : "Failed rendering stage",
    "message" : "failed rendering template expression"
  }, {
    "severity" : "FATAL",
    "cause" : "Incorrectly defined variable(s): waitTime (expected type 'int' found type 'String')",
    "message" : "malformed template configuration"
  }, {
    "severity" : "FATAL",
    "cause" : "Incorrectly defined variable(s): waitTime (expected type 'int' found type 'String')",
    "message" : "malformed template configuration"
  } ],
  "mptRequestId" : "f4e8ddca-a575-43ac-865e-aad92032870f",
  "trigger" : {
    "type" : "manual",
    "user" : "user"
  }
}
```

**Comment by rossedman** [comment]
Adding to this if I remove the variable from the UI there is a problem directly 

If I try to load this template it still fails.

```
schema: "1"
id: root-template
metadata:
  name: Simple wait template
  description: Extendable root template
stages:
- id: wait1
  type: wait
  config:
    waitTime: 5
```

**Comment by danielpeach** [comment]
This fix hasn't been released yet. It should be included in 1.4.3.

**Comment by rossedman** [comment]
@danielpeach ah good to know. I thought it was released with 1.4.2. Thanks so much.

**Comment by lwander** [comment]
Seeing that this is fixed & we're aiming to release 1.5.0 in place of 1.4.3 I will close this.

**Comment by rossedman** [comment]
@lwander cool thanks!
