### ISSUE TITLE
CloudDriver Stops Receiving Tags From GCR Until Restarted

### ISSUE THREAD

**Issue by brantburnett** [spinnaker/spinnaker#2039]
*Cloud Provider*

Google Container Registry

*Environment*

I am running Spinnaker 1.4.2 deployed onto a small, dedicated Kubernetes 1.8 cluster running in AWS, one pod for each service.

*Feature Area*

Loading tags from Google Container Registry

*Description*

At first pulling tags from GCR works fine.  But after a few days it will suddenly cease.  Calls to Gate to retrieve tags return a 400 error.  Logs from Clouddriver are included below.  Recycling the Clouddriver pod fixes the problem for a few more days.

*Steps to Reproduce*

1. Configure GCR using a service account per these instructions: (https://www.spinnaker.io/setup/providers/docker-registry/#google-container-registry).  This includes enabling Google APIs, creating a service account, and using the JSON file to configure access via Halyard.
2. Use Halyard to deploy the configuration
3. Observe that Deck will show tags for registries in GCR
4. Wait a few days and observe that Deck no longer shows tags, and Developer Console will show 400 responses for the request
5. Recycle Clouddriver and observe that functionality in Deck is restored 

*Additional Details*

Note: redacted actual Docker registry names below

```
2017-10-17 14:49:51.043 ERROR 1 --- [tionAction-2905] .d.r.p.a.DockerRegistryImageCachingAgent : Could not load tags for xxxx/yyyyy
2017-10-17 14:49:51.062 ERROR 1 --- [tionAction-2905] .d.r.p.a.DockerRegistryImageCachingAgent : Could not load tags for xxxx/zzzzz
2017-10-17 14:49:51.063  WARN 1 --- [tionAction-2905] n.s.c.d.r.a.v.a.DockerBearerTokenService : Your registry password has trailing whitespace, if this is unintentional authentication will fail.
2017-10-17 14:49:51.236  WARN 1 --- [tionAction-2905] n.s.c.d.r.a.v.a.DockerBearerTokenService : Your registry password has trailing whitespace, if this is unintentional authentication will fail.
2017-10-17 14:49:51.373  WARN 1 --- [tionAction-2905] n.s.c.d.r.a.v.a.DockerBearerTokenService : Your registry password has trailing whitespace, if this is unintentional authentication will fail.
```

We had also noticed the issue previously when running in LocalDebian mode, though we didn't do complete research or collect logs at that time.

**Comment by joshughes** [comment]
I have also experienced this issue with GCP and Google Container Engine

**Comment by selslack** [comment]
I've also experienced issues with GKE+GCR.

**Comment by ryan-mf** [comment]
I moved my Spinnaker deployment from single instance to Halyard + Kubernetes about two weeks ago, and noticed this same behavior about 2-3 days after initial deployment. I'm now having to kick (delete) the clouddriver POD every 2-3 days when it stops talking to our GCR, so that the clouddriver replicaSet sees the down replica and recreates it, and we're good for another 2-3 days. I've gone through our logs to investigate but haven't been able to find anything interesting that sheds light on the issue.

Is there an easy way to turn on more debug-level logging in clouddriver when running in K8S via Halyard, so I could provide those logs to this ticket when it happens again?

**Comment by lwander** [comment]
I would recommend reducing your polling interval - 

`hal config provider docker-registry account edit <gcr account> --cache-interval-seconds 120`

default is 30, and it looks like you're being rate-limited.

**Comment by ryan-mf** [comment]
Ok, I've bumped all of my docker registries (2x GCR, 1x dockerhub) to 120 second caching interval and I'm restarting via Hal. We'll see if this helps.

**Comment by lwander** [comment]
SG - there is a 24 hour rolling window that these rate limits are calculated along - so it might be a little while.

**Comment by joshughes** [comment]
@iwander if we were being rated limited... why would a restart fix the issues ?

**Comment by joshughes** [comment]
I suppose if every time we restarted cloud driver may jump from one node to another... thus changing public IP addresses... I will see if that is the case on the next time this happens... but a restart seems to always fix the issue... and it seems to only happen for some tags and not others when the issue does occur.

**Comment by ryan-mf** [comment]
@joshhughes I had the same thought - why does restarting fix it? My thinking was that it seems like clouddriver gets permanently wedged on a registry once it runs into trouble. If that's the case, that's definitely a bug.

**Comment by joshughes** [comment]
I am applying the config change now... so will report back if it makes a difference...

**Comment by lwander** [comment]
Yeah if you switch IPs you'll temporarily get around the rate limit

**Comment by bartekurbanski** [comment]
the provided solution does not work for us, restarting clouddriver is the only way and works as a charm

**Comment by tjma2001** [comment]
I am having the same issue with Spinnaker 1.5.0

Deleting the clouddriver pod caused a whole lot of "held up" builds to trigger.

**Comment by ryan-mf** [comment]
@lwander I reduced my polling interval as recommended, I've even triple it to 180 seconds, and invariably I still have this issue. Every time, just kicking the clouddriver POD fixes it. Doesn't seem like a throttling problem, or if it is, odd that my 2 node (so only 2 IP's a POD can come from) GKE cluster is always finding a way around the throttle after a restart.

Really feels like something else is wrong.

**Comment by adamresson** [comment]
Agreed something else is up rather than rate limiting. I have two pipelines that trigger on image builds that come from the same repo, so the new docker images got pushed up within seconds of one another and only one deployed (95% of time this works, except when clouddriver gets in this state). They are both in the same GCR Registry, just different images. Same thing, kicking clouddriver fixed it, and the 2nd one deployed. Nothing seems interesting in the logs.

**Comment by lwander** [comment]
Are there any suspicious log messages?

**Comment by brantburnett** [comment]
@lwander 

I still have the odd logs from the initial issue report, which include "Your registry password has trailing whitespace".  But my registry password doesn't include trailing whitespace, and I've only noticed this message after clouddriver begins failing.

**Comment by adamresson** [comment]
Mine too always had that message. I assumed it was because with GKE, my 'password' is really the service token.

**Comment by ryan-mf** [comment]
@lwander I haven't been able to find any suspicious log messages in my deployment (running via Kube on GKE). However, right now I have to kick the clouddriver POD every couple days to keep it communicating with our GCR. As mentioned above by others, it only will affect certain "applications" when it happens, even though two or more applications use the same docker registry account - so one application will keep working, and I can manually choose a tag to deploy, but another application will lose the ability to get tags from that same registry and I can no longer manually deploy either (spinning gear trying to get the tags). Each time I kick the clouddriver POD, it fixes it.

**Comment by lwander** [comment]
Seems this is a bug in GCR, here is the fix: https://github.com/spinnaker/clouddriver/pull/2215

**Comment by sami9gag** [comment]
I just traced that fix and if I'm reading this correctly, it should be included in Spinnaker 1.5.4 (clouddriver 1.0.4). We are still seeing this issue in our environment, even with these versions.

**Comment by adamresson** [comment]
Yeh, I saw this as well last week again with 1.5.4, altough not this is the first time since I deployed 1.5.4 that I've seen the issue, when previous I was seeing it every 2-3 days.

**Comment by brantburnett** [comment]
I am still seeing an issue as well, though much less frequently.  However, I don't yet have confirmation if the logs are the same or not.  Does someone else have logs from around the time of failure?

**Comment by sami9gag** [comment]
Here is a portion of the logs we are seeing 
https://gist.github.com/sami9gag/bdfdb4bf0e166295bdbe7ee9bb922c7d

**Comment by bseibel** [comment]
I'm seeing this in 1.5.4 as well. The registry is added without specifying specific repositories and we set cache-interval-seconds 300. 

In our case its only affecting retrieving tags for maybe 3 of the 20+ images we have which throw the same 401 as mentioned above:

```
2018-01-31 15:29:18.336 ERROR 10858 --- [utionAction-982] .d.r.p.a.DockerRegistryImageCachingAgent : Could not load tags for xxx/xxx

retrofit.RetrofitError: 401 Unauthorized
        at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
```

**Comment by brantburnett** [comment]
I can now confirm that my logs match @bseibel's logs, and that restarting the service corrects the issue.  This issue happened approximately 2 days after the latest restart (though that restart was due to a Spinnaker deployment, not this issue).

**Comment by tjma2001** [comment]
In the interim I have created a workaround, its a simple go application that deletes your clouddriver pods every 24 hours. You can configure the cron schedule from the yaml file in the repository

https://github.com/tjma2001/clouddriver-pod-delete

**Comment by joshughes** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/585

I found and followed the instructions here for the service account roles... have not seen the issue again.

**Comment by brantburnett** [comment]
I can confirm that adding the extra roles did not resolve the issue for us.  We're currently running 1.7.2.

**Comment by svenbovens** [comment]
We have 2 instances of Spinnaker:
1.5.0 we need to restart clouddriver each Friday, so this lasts about a week before getting the error
1.6.1 we just implemented an automated nightly restart. It was restarted +/- 7 hours ago and now we already got the error again. It seems to be random and a lot more frequent than the older version. Would be nice if this could be part of a liveness probe so the container gets restarted automatically when it happens.

**Comment by adamresson** [comment]
Just FYI, restarting clouddriver in the middle of a deploy can also lead to unexpected results where the new server group comes up, but the old server groups don't downscale/get removed.

**Comment by KeisukeYamashita** [comment]
I am having the same issue. Moreover, `hal deploy apply` doesn't work and get stuck with the Deploy of the `clouddriver` . I can't get triggers. How can I solve this?

```bash
* Deploy spin-clouddriver
  Deploying spin-clouddriver via provider API: Manually deploying spin-clouddriver
```

**Comment by adamresson** [comment]
Any resolution/workarounds that people have found to fix this issue? It's really hindering productivity.

**Comment by mhinc14** [comment]
how are you guys restarting cloud-driver. Steps to do so would be very helpful as we are also experiencing the same issue.

**Comment by adamresson** [comment]
In my case @mhinc14, spinnaker is running in Kubernetes, so I simply delete the cloud driver pod and then the replica set recreates it.

Here's a quick one liner that can do that.
```
kubectl delete $(kubectl get pods -l app=spin -l stack=clouddriver -o name)
```

**Comment by brantburnett** [comment]
I'm still seeing this issue in 1.8.1, here's the latest logs that seem to be related:

```
2018-07-18 22:16:14.526  INFO 1 --- [ionAction-10790] c.k.v.p.a.KubernetesInstanceCachingAgent : Describing items in k8s-spinnaker/KubernetesInstanceCachingAgent[1/1]
2018-07-18 22:16:14.527  WARN 1 --- [ionAction-10784] c.n.s.c.d.r.a.v.c.DockerRegistryClient   : Error encountered during catalog of null401 Unauthorized
2018-07-18 22:16:14.528  INFO 1 --- [ionAction-10784] .d.r.p.a.DockerRegistryImageCachingAgent : Describing items in stage-registry/DockerRegistryImageCachingAgent[1/1]
2018-07-18 22:16:14.528  INFO 1 --- [ionAction-10784] .d.r.p.a.DockerRegistryImageCachingAgent : Caching 0 tagged images in stage-registry/DockerRegistryImageCachingAgent[1/1]
```

Note that we have two different GCR Docker Registries (with different credentials), and they seem to stop working independently.  Additionally, the only fix is still recycling clouddriver.

**Comment by brantburnett** [comment]
@lwander 

I've been doing some research in the code trying to identify the source of this problem.  I don't really know Groovy, so please bear with me if I'm way off base.

When using GCR, authentication is configured using a username and password file.  The username is "_json_key", and the password file is a JSON object containing the auth key (along with some other information) for a service account.

When using this auth method, the first request to the Docker Registry via the client will use Basic auth in the Authorization header, basing the username and password file Base64 encoded:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy#L402

I've tested with Postman, and confirmed that these requests will succeed directly, without failing and returning WWW-Authenticate headers.  This means all subsequent requests will still not have a token stored in the cache, and will continue to use Basic auth and succeed.

However, imagine the scenario where one of these requests were to fail with a 401.  Perhaps a hiccup in GCR, or perhaps related to the fact that the password file seems to be read from disk on every request.  In this case, it will fall through and attempt to acquire a token using the WWW-Authenticate header, which refers to the realm "/v2/token" and service "us.gcr.io" in my tests.  At this point, a token is issued and cached in the token cache.

However, for some reason with GCR this token does not appear to function.  It does allow you to pull the _catalog endpoint successfully if you provide the Bearer token.  However, any request to actually get tags using this token seems to fail with a 401:

```json
{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "Requested repository does not match bearer token resource: project-1234/myreponame"
        }
    ]
}
```

Additionally, this particular 401 doesn't include a WWW-Authenticate header:

```
Alt-Svc →quic=":443"; ma=2592000; v="44,43,39,35"
Cache-Control →private
Content-Encoding →gzip
Content-Type →application/json
Date →Thu, 19 Jul 2018 14:30:30 GMT
Docker-Distribution-API-Version →registry/2.0
Server →Docker Registry
Transfer-Encoding →chunked
X-Frame-Options →SAMEORIGIN
X-XSS-Protection →1; mode=block
```

Therefore the auth process short circuits here: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy#L418

However, the token was already cached in the dictionary, and will continue to be used for all requests and fail.

I'm not 100% sure what the best fix might be, assuming my interpretation is correct, since this seems like it may be a problem with GCR that requires a workaround.  My first thought would be a slight change int he 401 handling behavior.  In any of the cases where reauth fails (i.e. no WWW-Authenticate header, etc) clearing the old token out of the cache seems like the best bet.  At this point we know that the token is invalid and that it wasn't replaced with a new call to tokenService.getToken, so it seems safe for all registries.  And for GCR the current request would still fail, but the next request would then succeed.

**Comment by brantburnett** [comment]
TWIMC, I've been running a patched version of clouddriver (https://github.com/brantburnett/clouddriver/commit/188fb31f9e5e39e15e4f86916db296be8f54278a) in our Spinnaker 1.8 environment for the last 3 days and we have not had to recycle our pod in that time.  That's not a definitive result, but it is encouraging.

**Comment by lwander** [comment]
Great work @brantburnett -- as far as 
> However, for some reason with GCR this token does not appear to function. It does allow you to pull the _catalog endpoint successfully if you provide the Bearer token. However, any request to actually get tags using this token seems to fail with a 401:

goes, I think it's because it fails to provide a scope, and as a result the returned token doesn't have the correct permission to read tags. You can verify this by turning up logging in the TokenService and forcing Spinnaker to grab a new token with each request.

The fix looks good! Please open a PR if you have a chance :)
