### ISSUE TITLE
GCE : Deck UI doesn't allow to enter port name for port mapping

### ISSUE THREAD

**Issue by sweetib** [spinnaker/spinnaker#2490]
**Title**
Deck UI doesn't allow to enter port name for port mapping

**Cloud Provider**
GCP

**Environment**
OS: Ubuntu Xenial 16.04
Version of Spinnaker sub-services used:
```
spinnaker                        0.83.0        
spinnaker-clouddriver            1.773.0       
spinnaker-deck                   2.1176.0     
spinnaker-echo                   1.543.0      
spinnaker-fiat                   0.39.0       
spinnaker-front50                1.120.0      
spinnaker-gate                   4.18.0       
spinnaker-igor                   1.87.7       
spinnaker-keel                   0.8.0        
spinnaker-monitoring-daemon      0.6.0        
spinnaker-monitoring-third-party 0.6.0
spinnaker-orca                   6.0.0        
spinnaker-quip                   0.52.0-3     
spinnaker-rosco                  0.103.0      
spinnaker-rush                   1.25.0-3
```

**Feature Area**
Spinnaker Deck UI

**Description**
Not able to specify port name in deploy step for port mapping through UI, Its giving a list box but doesn't list anything and doesn't save provided text input

1.
![alt text](https://lh3.googleusercontent.com/0fU9b3i8xCbgm_4t18JbOMft7pfsgV_Z5ZD5TzruvJfsCvQRZmw04bA_V9JbT5mGpYc_M3IE59z45v3ffSW6nD1kFIiuOffw43s1AA7QHLj3lY1gHWtsej6yu1nnmV2aVsmRDiV7JD51D2QBpmqbMmh9_4oQolYqeYNaHq5w8_2qht-vUlsipx9tzdZDvu2suLo3uvzBJfwU7Fa8EkJfKwt5Rx4DJUzw61o4w8fp8VihzdwNQ1S06TVsAfgisv6gMPh3BhMWYiUNt8udcSSPP_e7hF3jaX8CLh-OmWcvDRmSsL1GeZQ0ay1lblhL4d0DRmwAQIlOUHxevFMQoqQRP9nAah-SvNPxuZIRYASkQ6Q23lqga47SeJDx6floTxFKxuWEULqZ-A8uv8b-bhASx88bv4TcTdVZwmguU2kWLlpfh4j0fWn-unSDNPlDbkao68EVZCZZsYWBrc_7YC7D4trkEp7DOXlPtQ747rsYIdG_OLc5HdIsB_kzVKizRacS7h5DWSytsTGZEF0U73UBVKnJE1DShR_-w1APmd6YlsKgIHr8ALHhOyVAbjL7hlVi2_vQf86DnX79KtKQ9tq3UYfp1r408mDrAxICAwXeLGnBbfBo3ZQitkTaEPOma6MIo0EC_aY1r_6MS9-ZR333jdV8w9FTUso=w596-h288-no)

2.
![alt text](https://lh3.googleusercontent.com/-v09j0CBwRXMWpSIXtAupM-U6aJ-MjvQkyprVsygIs6urzlEH39H4FtlUNumuHtzlipbp7KheBBiGzrdwYCsBroaWITPQMFGC0jvG4rCSiazRUPZfXvoMbJ44aUneDX7Qyb-1pBa28Bp26nu2Pwn4o0oWjAGN8CkMLdvfhMrkTYOXpfyZ42Nv99WG9JPWtx1xKCrGEN9YSNsbzHDuIsgPCSsRcBxOUpLd6pDKPUQHQ9Yfxe7yKCue8zuLYlb7fJFNAVc6HYCcWRkNVjo-ZuaJpdbrgXBQlxLFd8hbovUIgMMQQAeLbhV_cfpPJTZRiX5gHNT9Zu7sAW0-i481Dj52d19FwlnG_ce50qIAusHPojNkYnF2KdCQQUrqwJT6ne-4BgK4cXrOjk8QBgCG_ELC2nO_nJA7glWQurBs2XgUU0ENBKk8wU3SUwzZpcf1yjSQ-SblWUCt90qevEOZM45IW_HNM8oFYc7Q2kYE_GcJZwcFQeOIVTlFZ6P1ZjmFzipKjccq9E21SzpXq02R6-etn6Bz7a0T84TXJEdwdoYUQLcjhCYWv0fb5FndWG3Z5o1rOeaD5kcAg8GL_Fw-c-kaLu2WNiqijNpf5iJGA=w612-h165-no)

3.
![alt text](https://lh3.googleusercontent.com/WWNJeDNDowAyqS5I5lIj9v0OCYqnZwmUCWb511Z7T6DkjBjDoZ9ZFJrVRvvQbPh8gMWz8IZZz_1qdz69YqQFjMjURS-TEdLtOLYHgfS-gPbdnzrOeG59ysk15itNmJZWH9mxAM0YQrmUCImBtxtYExukeBGP_ReiOhAe23xeqoFBlQ9c38Ke-yED4ZiYQAP3U1hJoZ5rkeoTFwWvMGBuwy3Xf9uLMxRl5NdK7lJpmQFujQ73NFJvS4krsdP4CgGKrop2sRlRFpWGvPe_33tQP6iM-Hw6rQCcDOkWYfdc1GIEOGa_BTHUAL7MAxe2WV6mZhFcmuQexHdJV6wmPsT-2p198pcDzOJWCTBnUE4WHg5kw1bqA8N7NGB6qeGqk2epuzOPpk6qNWd_vSnaoRGxDnDT91kIXEpbN6XL_GbXJbT4sd2YTeddEmY3i_h5UMy27IaJQiDOJoUCvNyQ8SHbjCkQl49cvUUCNCMsMeg0ccExF6VQXKN_vNE35QdZr15V5PFOfbhe89Y_4s_Ro-VmQ5l-llY4U3CtVp-5TuFPIgtREcdXCrblt8r7B1y3xk6_SSLAP9tHnc6ZtDvkPXSdm5Sbz68pJiGAmWadvQ=w558-h156-no)

**Error in Deploy Stage**
```
400 Bad Request { "code" : 400, "errors" : [ { "domain" : "global", "message" : "Invalid value for field 'resource.namedPorts[0].name': ''. Must be a match of regex '(?:a-z?)'", "reason" : "invalid" } ], "message" : "Invalid value for field 'resource.namedPorts[0].name': ''. Must be a match of regex '(?:a-z?)'" }
```

I have used temporarily fix by manually editing the pipeline json and setting the port name 
```
        "namedPorts": [
              {
                "name": "http",
                "port": 80
              }
            ]
```

Looking forward for fix for this issue.

**Comment by ezimanyi** [comment]
Being addressed in spinnaker/deck#4938

**Comment by ezimanyi** [comment]
Fixed in spinnaker/deck#4938.

**Comment by sweetib** [comment]
I have upgraded deck to ` 2.1179.0` and i am still facing this issue :( not sure what else need to be done @ezimanyi

**Comment by sweetib** [comment]
When we create a LB we don't see details of portname under backend services is it expected? 

while creating : 

![alt text](https://lh3.googleusercontent.com/1qlKOQv0ccH2KRwEp80FMNETxKwBFMPodkUUTg7RI3IUfu9kOiYrk3OsvNaf_VfwmMbyI7E9SCHFeb2ISAW65WMdrEJ_Xc4nVFmXzw8ejmbdDyRAMa2ODHQHE5BHihNygOWmLZoB0PNhKhs9BDpNSI_MO7WzvAg9lhDYcjVmWmKAD0pBck8jMx2o6JiIPV_MYoFwH785z3GquXdY2xtWLKX2gbR2i9YF3Bhz5pPchQ-3dUGU815WI7jNSpUNgOAC7yGC6dwmZPVzUq4x86C1qrF5Scfkkua7QXJSUPt3bWsNHz1bDHgAlweer5Wd2nzsJK1u04issPoUsKcBzZAJchwTz6tGd2ROuoEEXcs6xq9C3IX-wZius1CaD6bS3ZvGr6l6wMCsILVh7bA_-oquaJefuvlUSidkI91lEQfHj5j51nAK2A5yaNNrrfGUzyqsKTyn4LaSg1aWId6v15zoVjEDSAQZomARtL7dHDfKf_A0i8YnKABcA2afKogIhBZESbjkeA8jKJforfT3CeaSASi2xBOWCN6gkdFF5pTOWbPyoerfYqbm_IptF-tekedfESqyxcqxvf4GXmswQKl-wp2E4tE6BUvZ6PPcZA=w507-h262-no)

after creating : 
![alt text](https://lh3.googleusercontent.com/Bn6uUmXI2z0z2t2x0CKcCerAc18BqaowSTvuWp6Nmv5qlVhW4QGaClWTNWiAX6PY_KRLbGyJr-b_IIoeZpuvBR63QK3W-PgOIK_UIlXdFg6B3hyhd3JAghQqHfetvldS-lm99Yk8eD6Yzq1ZTS39gFqx-FuJF0VulsQhwwOObmw5dAfkoPon2fVMPlGxG3hkleZOu8tXrwdbVOjXNh39TXCyo4tjaPfjHr-aN1Ts8qeesQHCw4E0HuJP1cTNhke1kbjG8JQsEDaJgdJlepjf-vNLvmUFCSKqP4uQTbGStFaNDDeI-9gU9MgCusO2HhvZH3XOwkRnF4Ce_FU7bdXEYGQn4e8EhXA81sRE3eRDEcI6dqk-LW81XFlMMOOnGucs_0mL2ts084YhvepGcUaGQY90pFW3kQmUWuFyVUyeMG2m7AcqKm9rKZscUy_oQXgFYJTIlvsjQKayUZu8PSf7jRdznCB6NrVQlJQFewfVoKhz_6NKhTPYxDpqgecNxP2dmz10Uq-ZUgPMv4hFufMeMegwZSvOEqZXXe2XwXP8NG5QYE9cmBaiXGESmfufAADusGLCAssV4b2ypVHm0o_dX7bK9QbsAIg9lQZ6uA=w223-h189-no)

**Comment by ezimanyi** [comment]
@sweetib : Sorry for the delay in getting back to you; I was out of the office the first part of the week and am just catching up now.  The commit that fixed the bug was f52d61a7c1e440259c0b9addce8fb4e9183ff792, which looks like it first appeared in deck 2.1180.0.  Can you try upgrading to that version and letting me know if you still see the issue?

**Comment by ezimanyi** [comment]
@sweetib : Sorry, I got confused and linked to the wrong commit above.  This was fixed in https://github.com/spinnaker/deck/pull/4938/commits/5c1c1daac293a7fbc5648ff22b30c5b03f490ece which is included in 2.1179.0 which you're using.

However, the fix also depends on the following commit to gate: https://github.com/spinnaker/gate/pull/511/commits/69ed0528968b2169875357f021127a15363dad05, so this unless you are running a recent enough version of gate that includes that commit, you'll still experience the issue.

Please let me know if this helps or if you're still having issues!

**Comment by sweetib** [comment]
Thanks, It works in the latest setup of spinnaker. Apologies for reverting so late.
