### ISSUE TITLE
Release 1.11 - Pipeline Non-Starts - Tag Hydration Issues

### ISSUE THREAD

**Issue by kskewes** [spinnaker/spinnaker#3737]
### Issue Summary:

We updated to 1.11 from 1.10.5 on Friday morning. Deployed into Kubernetes.
Initially pipelines were manually triggering fine (I think was using latest image instead of our tagged image in hindsight). 
Later in the day when verifying promotion of artifacts between environments we noticed that docker image tags were not populating in `Deploy Manifest` stages.
Deploy Manifest stages were deploying `latest` tag only.

Rolled back to 1.10.5 and image tags were correctly applied.

### Cloud Provider(s):

Kubernetes

### Environment:

Kubernetes 1.12

### Feature Area: 

...

### Description:

Some comments from Slack channels.
```
- there is a bug in 1.11.0, it doesn't pick docker image tag when running manual build. The deploy yaml always have the default tag rather than having trigger tag. This is a very big bug and did break our dev environment completely until we realised this and rollback.
- I met the same issue after upgrade from 1.10.5 to 1.11. guess some bug in the new version.
- Since upgrading to 1.11 this morning we're having trouble with pipelines triggering.  If you click on Start Manual Execution, it just spins for a few seconds and goes away, the pipeline never starts.  Also some automatic triggers aren't firing.  Other pipelines work fine, though.  I haven't been able to track down anything useful in the logs yet.  Anyone else have any experience/advice?  @Eric Zimanyi could this be related to your trigger work in 1.11?  I haven't turned on any new feature flags yet.
``` 

### Steps to Reproduce:

This was tested with both:
- `Manual` trigger of a pipeline with a Docker Trigger, selecting docker image tag to use.
- `Find Artifact From Resource` stage to pull image from another stage. It would find the right image but not apply during a subsequent `Deploy Manifest` stage.

### Additional Details:

Can search back through logs but not able to upgrade to 1.11 to track down today.

**Comment by brantburnett** [comment]
I have also seen problems starting pipelines using manual triggers for:

- A pipeline with no automatic triggers (using Find Image From Cluster as step 2)
- A job with a Jenkins trigger

I captured some logs in the first case (no automatic trigger).  From echo:

```
2018-12-17 12:49:21.628  INFO 1 --- [IoScheduler-151] c.n.s.e.p.monitor.TriggerMonitor         : Found matching pipeline stagecustsvc:Deploy to Production
2018-12-17 12:49:21.628  INFO 1 --- [IoScheduler-151] c.n.s.e.p.orca.PipelineInitiator         : Triggering Pipeline(stagecustsvc, Deploy to Production, f3284c09-c2c1-4086-9c26-750b4718c572) due to Trigger(null, manual, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
2018-12-17 12:49:21.630  INFO 1 --- [it-/orchestrate] c.n.s.e.p.orca.OrcaService               : ---> HTTP POST http://spin-orca.spinnaker:8083/orchestrate
2018-12-17 12:49:21.708  INFO 1 --- [it-/orchestrate] c.n.s.e.p.orca.OrcaService               : <--- HTTP 403 http://spin-orca.spinnaker:8083/orchestrate (78ms)
2018-12-17 12:49:21.709 ERROR 1 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Retrying pipeline trigger, attempt 1/5
2018-12-17 12:49:24.808  INFO 1 --- [pool-1-thread-1] c.n.s.echo.services.Front50Service       : ---> HTTP GET http://spin-front50.spinnaker:8080/pipelines?restricted=false
2018-12-17 12:49:24.849  INFO 1 --- [pool-1-thread-1] c.n.s.echo.services.Front50Service       : <--- HTTP 200 http://spin-front50.spinnaker:8080/pipelines?restricted=false (40ms)
2018-12-17 12:49:26.710  INFO 1 --- [it-/orchestrate] c.n.s.e.p.orca.OrcaService               : ---> HTTP POST http://spin-orca.spinnaker:8083/orchestrate
2018-12-17 12:49:26.720  INFO 1 --- [it-/orchestrate] c.n.s.e.p.orca.OrcaService               : <--- HTTP 403 http://spin-orca.spinnaker:8083/orchestrate (10ms)
2018-12-17 12:49:26.720 ERROR 1 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Retrying pipeline trigger, attempt 2/5
```

From orca (some parts redacted):

```
2018-12-17 12:49:41.744  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.c.OperationsController           : [] received pipeline f3284c09-c2c1-4086-9c26-750b4718c572:{"application":"stagecustsvc","name":"Deploy to Production","id":"f3284c09-c2c1-4086-9c26-750b4718c572","parallel":false,"disabled":false,"limitConcurrent":true,"plan":false,"respectQuietPeriod":false,"triggers":[],"stages":[...],"notifications":[...],"receivedArtifacts":[],"trigger":{"type":"manual","enabled":false,"user":"...","parameters":{},"rebake":false,"dryRun":false,"eventId":"2f8e4c03-d5e3-41cf-9c86-da629c0c6852","artifacts":[]}}
2018-12-17 12:49:41.745  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.p.e.ExpressionTransform          : [] Failed to evaluate ${#stage('Deploy').context.clusters[0].stack}, returning raw value EL1006E: Function 'stage' could not be found
2018-12-17 12:49:41.745  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.p.e.ExpressionTransform          : [] Failed to evaluate Start Deploy of ${execution['application']} to  ${#stage('Deploy').context.clusters[0].stack}, returning raw value EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.LinkedHashMap'
2018-12-17 12:49:41.746  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.p.e.ExpressionTransform          : [] Failed to evaluate Start Deploy of ${execution['application']} to  ${#stage('Deploy').context.clusters[0].stack}, returning raw value EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.LinkedHashMap'
2018-12-17 12:49:41.746  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.p.e.ExpressionTransform          : [] Failed to evaluate ${#stage('Deploy').context.clusters[0].stack}, returning raw value EL1006E: Function 'stage' could not be found
2018-12-17 12:49:41.746  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.p.e.ExpressionTransform          : [] Failed to evaluate Deployed ami ${#stage('Find Image from Cluster').context
.amiDetails[0].ami} of ${execution['application']} to ${#stage('Deploy').context.clusters[0].stack} Deploy Duration: ${new java.text.SimpleDateFormat('HH:mm:ss').format(#stage('Deploy').endTime - execution['startTime'])}, returning raw value EL1006E: Function 'stage' could not be found
2018-12-17 12:49:41.746  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.p.e.ExpressionTransform          : [] Failed to evaluate Deployed ${execution['application']} to  ${#stage('Deploy').context.clusters[0].stack}, returning raw value EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found ontype class java.util.LinkedHashMap'
2018-12-17 12:49:41.747  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.p.e.ExpressionTransform          : [] Failed to evaluate ${#stage('Deploy').context.clusters[0].stack}, returning raw value EL1006E: Function 'stage' could not be found2018-12-17 12:49:41.747  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.p.e.ExpressionTransform          : [] Failed to evaluate Failed to deploy ami ${#stage('Find Image from Cluster')
.context.amiDetails[0].ami} of ${execution['application']} to ${#stage('Deploy').context.clusters[0].stack} Deploy Duration: ${new java.text.SimpleDateFormat('HH:mm:ss').format(#stage('Deploy').endTime - execution['startTime'])}, returning raw value EL1006E: Function 'stage' could not be found
2018-12-17 12:49:41.747  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.p.e.ExpressionTransform          : [] Failed to evaluate Failed to deploy ${execution['application']} to  ${#stage('Deploy').context.clusters[0].stack}, returning raw value EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.LinkedHashMap'
2018-12-17 12:49:41.747  INFO 1 --- [0.0-8083-exec-1] c.n.s.o.c.OperationsController           : [] requested pipeline: {"expressionEvaluationSummary":{"Failed to deploy ami #stage( #root.execution, 'Find Image from Cluster').context.amiDetails[0].ami of execution['application'] to #stage( #root.execution, 'Deploy').context.clusters[0].stack Deploy Duration: new java.text.SimpleDateFormat('HH:mm:ss').format(#stage( #root.execution, 'Deploy').endTime - execution['startTime'])":[{"description":"Failed to evaluate [text] EL1006E: Function 'stage' could not be found","exceptionType":"org.springframework.expression.spel.SpelEvaluationException","timestamp":1545050981747,"level":"ERROR"}],"Deployed ami #stage( #root.execution, 'Find Image from Cluster').context.amiDetails[0].ami of execution['application'] to #stage( #root.execution, 'Deploy').context.clusters[0].stack Deploy Duration: new java.text.SimpleDateFormat('HH:mm:ss').format(#stage( #root.execution, 'Deploy').endTime - execution['startTime'])":[{"description":"Failed to evaluate [text] EL1006E: Function 'stage' could not be found","exceptionType":"org.springframework.expression.spel.SpelEvaluationException","timestamp":1545050981746,"level":"ERROR"}],"Deployed execution['application'] to  #stage( #root.execution, 'Deploy').context.clusters[0].stack":[{"description":"Failed to evaluate [title] requested getter execution notfound on type class java.util.LinkedHashMap - EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.LinkedHashMap'","exceptionType":"java.lang.IllegalArgumentException","timestamp":1545050981746,"level":"ERROR"}],"Failed to deploy execution['application'] to#stage( #root.execution, 'Deploy').context.clusters[0].stack":[{"description":"Failed to evaluate [title] requested getter execution not found on type class java.util.LinkedHashMap - EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.LinkedHashMap'","exceptionType":"java.lang.IllegalArgumentException","timestamp":1545050981747,"level":"ERROR"}],"#stage( #root.execution, 'Deploy').context.clusters[0].stack":[{"description":"Failed to evaluate [environment] EL1006E: Function 'stage' could not be found","exceptionType":"org.springframework.expression.spel.SpelEvaluationException","timestamp":1545050981745,"level":"ERROR"}],"Start Deploy of execution['application'] to  #stage( #root.execution, 'Deploy').context.clusters[0].stack":[{"description":"Failed to evaluate [text, title] requested getter execution not found on type class java.util.LinkedHashMap - EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.LinkedHashMap'","exceptionType":"java.lang.IllegalArgumentException","timestamp":1545050981745,"level":"ERROR"}]},...
2018-12-17 12:49:41.748  INFO 1 --- [0.0-8083-exec-1] c.n.s.orca.front50.Front50Service        : [] ---> HTTP GET http://spin-front50.spinnaker:8080/pipelines/stagecustsvc?refresh=false
2018-12-17 12:49:41.754  INFO 1 --- [0.0-8083-exec-1] c.n.s.orca.front50.Front50Service        : [] <--- HTTP 403 http://spin-front50.spinnaker:8080/pipelines/stagecustsvc?refresh=false (6ms)
2018-12-17 12:49:41.807  WARN 1 --- [0.0-8083-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : [] Resolved [retrofit.RetrofitError: 403 ]
```

**Comment by ezimanyi** [comment]
I've fixed a few issues that I believe should resolve all of the reported bugs here:
* Including a Docker tag/digest on a manual execution now properly injects that into the pipeline
* There was an issue propagating authorization when using manual executions, so in some cases the pipeline would not start because it did not have the necessary permissions

I've pulled all the fixes into the 1.10 and 1.11 branches:
* 1.10.6 will have the fixes, though in the 1.10.x branch these bugs are behind the `window.spinnakerSettings.feature.triggerViaEcho = true;` deck flag.  Once you have 1.10.6 you can try turning on the flag to test manual executions if you'd like to test before fully upgrading to 1.11.
* 1.11.1 will have the fixes

Please let me know if you see any other related issues, or if the fixes do not address the above issues.  As noted above, toggling the `window.spinnakerSettings.feature.triggerViaEcho` flag is the way of testing if the issue is related to the work in this bug.  (The flag defaults to `false` in 1.10 and to `true` in 1.11.)

**Comment by brantburnett** [comment]
@ezimanyi 

I tried upgrading 1.11 with the new version of echo, and things were better, the pipeline was able to start.  However, I still encountered a problem.

In this case, I was manually triggering a pipeline with *no* automatic trigger, just a plain run with no artifacts to select.  The first stage is a Find Image From Cluster step.  This step failed with this message in Deck:

Exception ( Find Image )
Access denied to account stage

**Comment by brantburnett** [comment]
@ezimanyi 

At this point, I've already downgraded again, and due to log volume I don't have Spinnaker tied into a log persistence system yet.  So no logs, sorry about that.  I'll see if I can talk the teams into letting me try again.

As to the permissions questions:
- Yes, the user has permissions on the account.  The account is setup using separate read and write permissions, the user has both.
- There is no Run As user on the pipeline, as there is no trigger on the pipeline where it can be configured.  This job is always manually triggered.

Thanks,
Brant

**Comment by ezimanyi** [comment]
I'm going to close this as all of the fixes related to manual starts should be present in 1.11.1, though please re-open if there are any remaining issues.

I've opened https://github.com/spinnaker/spinnaker/issues/3766 to track the issue with Jenkins triggers.

**Comment by anup13kumar** [comment]
curl http://fiat-serverXXXXXX/authorize/my-service-account@spinnaker.xyz
Listing the applications but pipeline auto trigger not working not able to see any logs info also

**Comment by ezimanyi** [comment]
@anup13kumar : Can you please open a new issue with more details on the behavior you're seeing?  It's not clear that your issue is related to the current issue (and in any case the issues tracked here have all been fixed).
