### ISSUE TITLE
S3: ERROR Failed to ensure the required bucket exists: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden

### ISSUE THREAD

**Issue by imriss** [spinnaker/spinnaker#4554]
### Issue Summary:
When trying to add an S3 bucket, using the following command:
```
hal config storage s3 edit \
    --access-key-id $ACCESS_KEY_ID \
    --secret-access-key \
    --region $REGION; 
```
Faced this error:
```
Problems in default.persistentStorage:
- WARNING Your deployment will most likely fail until you configure
  and enable a persistent store.

Problems in default.persistentStorage.s3:
! ERROR Failed to ensure the required bucket "spin-46-456-345-2345"
  exists: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403
  Forbidden; Request ID: 67BD9FE5234505690673; S3 Extended Request ID: vMnfY+kUYtnGOiGjLee3m0STFk234g52345q14FFv7xA3oGjTFYh2ozm/ziveH3ko8coBonidqu2ETNE9TuyA=)

- Failed to edit persistent store "s3".
```

### Cloud Provider(s):
`Kubernetes V2`

### Environment:
`Halyard` deployed using `Docker` in a `Linux` VM:
```
docker run -p 8084:8084 -p 9000:9000 \
    --name halyard --rm \
    -v ~/.hal:/home/spinnaker/.hal \
    -v ~/.kube:/home/spinnaker/.kube \
    -e ACCESS_KEY_ID=ACCESS_KEY_ID \
    -e REGION=us-west-2 \
    -d \
    gcr.io/spinnaker-marketplace/halyard:stable
```
The `Spinnaker` would be deployed in a `Kubernetes` cluster on `EKS`.

### Feature Area:
`Storage`

### Description:
Cannot use `S3` for the persistent storage.

### Steps to Reproduce:
1. Deploy `Halyard` using `Docker.
2. Set up the `Kubernetes V2` provider.
3. Try to set up `S3` as the storage.

### Additional Details:

---

**Comment by imriss** [comment]
It has been resolved using the following along with adding a specific policy that gives permission to the `IAM` user for the specific `S3` bucket `BUCKET_NAME` that was created before creating the policy:
```
hal config storage s3 edit \
    --bucket $BUCKET_NAME \
    --access-key-id $ACCESS_KEY_ID \
    --secret-access-key \
    --region $REGION;
```

**Comment by codeSapience** [comment]
Hi. I faced a similar issue today. But I was able to resolve by not specifying `--region $REGION` option in the command.
Guess hal(-yard) implicitly specifies a region that works for you.
So what worked for me looked something like this:
```
hal config storage s3 edit  --bucket $BUCKET_NAME  --access-key-id $ACCESS_KEY_ID  --secret-access-key 
```

**Comment by techd1984** [comment]
I'm still getting this error while trying to setup s3 using IAM role that has access to s3 bucket mentioned.

hal config storage s3 edit --bucket=spinkinteg --assume-role=arn:aws:iam::123456:role/SpintestInt
- Get persistent store
  Failure
Problems in Global:
! ERROR No persistent store with name "s3" could be found
? Create a new persistent store with name "s3"

- Failed to get persistent store "s3".

**Comment by alexef** [comment]
I'm having the same issue. Any way to instruct halyard that it needs to assume a role to verify the bucket?

**Comment by alexef** [comment]
For the record, this was solved by passing the correct `.aws` credentials and AWS_PROFILE to the hal container.

**Comment by rcclemente** [comment]
@alexef 
How did you accomplist this 
```
For the record, this was solved by passing the correct .aws credentials and AWS_PROFILE to the hal container.
```

I am unable to find any information in the docs

**Comment by alexef** [comment]
@rcclemente it's been some time, what I remember was that:
- we mounted the `~/.aws` folder into `/root/.aws`
- we set the AWS_PROFILE environment variable to match the one in the config file
