### ISSUE TITLE
orca fails due to Data too long for column 'partition' for pipelines and orchestrations tables

### ISSUE THREAD

**Issue by yuliujin** [spinnaker/spinnaker#4750]
### Issue Summary:
orca fails due to Data too long for column 'partition' for pipelines and orchestrations tables when upgrade to 1.14+.

### Cloud Provider(s):
aws

### Environment:
1.14+

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
orca

### Description:
When we upgrade to Spinnaker 1.14, orca failed with the errors (see exception stack in "Additional Details"). It seems the "partition" column in both "pipelines" and "orchestrations" tables starts to be used since 1.14. It uses the hostname for the value and we happened to have a long hostname. After we alter the table to set the partition to varchar(255), everything works fine.

### Additional Details:
Exception Stack:
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: 2019-08-13 21:55:46.276 ERROR 20233 --- [     handlers-1] com.netflix.spinnaker.q.QueueProcessor   : [] Unhandled throwable from CancelExecution(executionType=pipeline, executionId=01DJ6DXAY94TMJWN6BE98W58ZA, application=spinnakerhalyardstg, user=xxx@xxx.com, reason=null)
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: org.springframework.dao.DataIntegrityViolationException: jOOQ; SQL [insert into pipelines (id, legacy_id, `partition`, status, application, build_time, start_time, canceled, updated_at, body, config_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on duplicate key update status = ?, body = ?, start_time = ?, canceled = ?, updated_at = ?, config_id = ? -- executionId: 01DJ6DXAY94TMJWN6BE98W58ZA]; Data truncation: Data too long for column 'partition' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'partition' at row 1
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: #011at org.jooq_3.11.6.MYSQL.debug(Unknown Source)
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: #011at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: #011at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: #011at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: #011at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: #011at com.netflix.spinnaker.orca.sql.JooqToSpringExceptionTransformer.exception(JooqToSpringExceptionTransformer.kt:31)
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: #011at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:251)
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: #011at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:365)
Aug 13 21:55:46 spinnakerhalyardstg-inf-0dddde2b2a428757b orca[20233]: #011at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:127)

**Comment by asher** [comment]
This should be fixed in the most recent orca release.

**Comment by asher** [comment]
Actually this is fixed by https://github.com/spinnaker/orca/pull/3030 which is targeted for release in 1.16. Just cherry-picked it in 1.15 in case there's another 1.15 point release.

**Comment by voiski** [comment]
Do I need to run any manual migration to fix it? I'm still having that issue in the version 1.19.2.
